// Roma OS service worker.
//
// Cache-first for the shell so the app opens instantly and works on the tube,
// network-first for nothing yet — there is no live data in Stage 1. The version
// string and the file list are generated by build.js; a hand-kept list goes
// stale the first time someone adds a file, and a stale cache on an iPhone is a
// bug that looks like "the app didn't update".
const CACHE = '__CACHE_VERSION__'
const PRECACHE = "__PRECACHE__"

self.addEventListener('install', (event) => {
  // Take over as soon as we are installed.
  //
  // This matters because of what came before: the previous Control Panel
  // shipped a Workbox worker registered with `registerType: 'prompt'`, which
  // never steps aside on its own. Without skipWaiting, that worker keeps
  // serving its own precached index.html and hashed bundles for as long as the
  // app is open, this worker sits in "waiting" forever, and the phone shows the
  // old app no matter how many times the URL is opened.
  // `cache: 'reload'` — fetch every file from the network, never from the
  // HTTP cache: Safari keeps old CSS and JS in front of the worker, and a new
  // worker precaching a stale bundle is exactly "the app didn't update".
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys()
    const stale = keys.filter((k) => k !== CACHE)
    await Promise.all(stale.map((k) => caches.delete(k)))
    await self.clients.claim()

    // If any cache we just removed did NOT belong to this app, we have replaced
    // a different one — its HTML is on screen right now and claiming control
    // does not re-render it. Reload those pages once so the switch completes
    // without the user having to know to refresh.
    //
    // Self-limiting: from the next version on, the only caches ever deleted are
    // our own older ones, so this never reloads anybody again.
    const replacedAnotherApp = stale.some((k) => !k.startsWith('roma-os-'))
    if (!replacedAnotherApp) return
    const clients = await self.clients.matchAll({ type: 'window' })
    for (const client of clients) {
      if ('navigate' in client) client.navigate(client.url)
    }
  })())
})

// Kept for the page to nudge an update along explicitly.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return   // fonts and the like go to the network

  event.respondWith(
    // ignoreSearch: index.html asks for bundle.js?v=…, the cache holds bundle.js.
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit
      return fetch(request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        })
        .catch(() => caches.match('./index.html').then((page) => page || Response.error()))
    }),
  )
})
