// Roma OS service worker.
//
// Cache-first for the shell so the app opens instantly and works on the tube,
// network-first for nothing yet — there is no live data in Stage 1. The version
// string and the file list are generated by build.js; a hand-kept list goes
// stale the first time someone adds a file, and a stale cache on an iPhone is a
// bug that looks like "the app didn't update".
const CACHE = '__CACHE_VERSION__'
const PRECACHE = "__PRECACHE__"

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

// A waiting worker only takes over when the page asks, so an update never
// swaps the bundle out from under a running screen.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return   // fonts and the like go to the network

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit
      return fetch(request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        })
        .catch(() => caches.match('./index.html').then((page) => page || Response.error()))
    }),
  )
})
